"""add address column

Revision ID: 805c4c6d50a9
Revises: c299c4bf1cf4
Create Date: 2024-06-08 22:19:36.811206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805c4c6d50a9'
down_revision = 'c299c4bf1cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
